if(WIN32)
    set(PLATFORM "pc")
    set(OS "windows")
elseif(UNIX AND NOT APPLE)
    set(PLATFORM "pc")
    set(OS "linux")
elseif(X86_IOS_SIMULATOR)
    set(ARCH "x86_64")
    set(OS "apple")
    set(ABI "ios")
elseif(IOS)
    set(ARCH "aarch64")
    set(OS "apple")
    set(ABI "ios")
elseif(APPLE)
    set(PLATFORM "pc")
    set(OS "apple")
elseif(EMSCRIPTEN)
    set(ARCH "wasm32")
    set(OS "unknown")
    set(ABI "emscripten")
else()
    set(PLATFORM "unknown")
    set(OS "unknown")
endif()

if(NOT ARCH) 
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(ARCH "x86")
    else()
        set(ARCH "x86_64")
    endif()
endif()

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" AND "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
    set(CLANG_MSVC ON)
endif()

set(LIB_PREFIX "lib")
if(CLANG_MSVC OR MSVC)
    set(LIB_PREFIX "")
    set(ABI "msvc")
endif()

if(NOT ABI)
    if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        set(ABI "gnu")
    else()
        set(ABI "unknown")
    endif()
endif()

if(VALGRIND)
    set(EXTRA_FLAGS ${EXTRA_FLAGS} "valgrind")
endif()

set(TARGET_PARTS ${ARCH} ${PLATFORM} ${OS} ${ABI} ${EXTRA_FLAGS})
list(JOIN TARGET_PARTS "-" TARGET_ID)
message(STATUS "TARGET_ID = ${TARGET_ID}")