#!/bin/bash

sudo apt-get -y update
sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev mesa-utils valgrind

mkdir -p build/install
cd build

apt list --installed >install/apt-package-list.txt

cmake -GNinja -DVALGRIND=ON ..
cmake --build . --target install
