#!/bin/bash

brew install openssl@1.1

TOOLCHAIN=`pwd`/cmake/ios-cmake/ios.toolchain.cmake

mkdir build
cd build
cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN -DPLATFORM=OS64 ..
cmake --build . --target install